# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ar-validations-json"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Hwang"]
  s.date = "2012-04-03"
  s.description = "Serializes ActiveRecord validations into JSON for use by rich-client apps."
  s.email = "sera@fhwang.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "ar-validations-json.gemspec",
    "lib/ar-validations-json.rb",
    "test/test_helper.rb",
    "test/unit/acceptance_test.rb",
    "test/unit/associated_test.rb",
    "test/unit/confirmation_test.rb",
    "test/unit/exclusion_test.rb",
    "test/unit/format_test.rb",
    "test/unit/inclusion_test.rb",
    "test/unit/length_test.rb",
    "test/unit/numericality_test.rb",
    "test/unit/presence_test.rb",
    "test/unit/uniqueness_test.rb"
  ]
  s.homepage = "http://github.com/fhwang/ar-validations-json"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "Serializes ActiveRecord validations into JSON for use by rich-client apps."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

